<a href="https://colab.research.google.com/github/IsagiTegaYoichi/Sentiment-Analysis-and-Topic-modelling-of-COVID-Vaccine-tweets2/blob/main/Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **READING DATA**

# New Section

In [ ]:
#Import Library to read Data
!pip install tweet-preprocessor
import pandas as pd
import preprocessor as p
import nltk
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

Collecting tweet-preprocessor
  Downloading tweet_preprocessor-0.6.0-py3-none-any.whl (27 kB)
Installing collected packages: tweet-preprocessor
Successfully installed tweet-preprocessor-0.6.0
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.

In [ ]:
#Read Extraction data

testdata=pd.read_csv('look.csv')

def preprocess_tweet(text):
    text = p.clean(text)
    return text
testdata['Tweet']=testdata['Tweet'].apply(preprocess_tweet)
testdata[['Tweet']].head()

                                               Tweet
0  I think the Q here is not could these women ha...
1  can you please confirm &amp; do something abou...
2                     This was me during my nd shot.
3  Fuck Big Pharma. Follow the money.Trust no one...
4  You know youve matured when you promise to do ...

In [ ]:

tokenized_tweet2=testdata['Tweet'].apply(lambda x: x.split())
tokenized_tweet2.head()
tokenized_tweet2=tokenized_tweet2.apply(lambda x:[lemmatizer.lemmatize(i) for i in x])
tokenized_tweet2.head()
stopped=['Follow','vaccine','covid','amp','amp','amp','Vaccine','people','People']
tokenized_tweet2=tokenized_tweet2.apply(lambda x: [item for item in x if item not in stopped])
tokenized_tweet2.head()
for i in range(len(tokenized_tweet2)):
    tokenized_tweet2[i]=' '.join(tokenized_tweet2[i])
testdata['Tweet']=tokenized_tweet2
testdata[['Tweet']].head()

                                               Tweet
0  I think the Q here is not could these woman ha...
1  can you please confirm &amp; do something abou...
2                      This wa me during my nd shot.
3  Fuck Big Pharma. the money.Trust no one.TRUST ...
4  You know youve matured when you promise to do ...

# **CLEANING TEST DATA**

In [ ]:
import sklearn
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer(max_features=5000)
testvector=vectorizer.fit_transform(testdata['Tweet'])

In [ ]:
testvector.shape

(13076, 5000)

In [ ]:
X_features = testvector
y=testdata['Analysis']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_features, y, test_size = 0.2, random_state = 1)
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
NaiveBclassifier = MultinomialNB()
NaiveBclassifier.fit(X_train,y_train)
y_pred=NaiveBclassifier.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,y_pred)*100
print(accuracy)
)

In [ ]:
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix\n\n', cm)

print('\nTrue Positives(TP) = ', cm[0,0])

print('\nTrue Negatives(TN) = ', cm[1,1])

print('\nFalse Positives(FP) = ', cm[0,1])

print('\nFalse Negatives(FN) = ', cm[1,0])

Confusion matrix

 [[  64  184  165]
 [   4 1153  114]
 [   2  178  752]]

True Positives(TP) =  64

True Negatives(TN) =  1153

False Positives(FP) =  184

False Negatives(FN) =  4

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

    Negative       0.91      0.15      0.27       413
     Neutral       0.76      0.91      0.83      1271
    Positive       0.73      0.81      0.77       932

    accuracy                           0.75      2616
   macro avg       0.80      0.62      0.62      2616
weighted avg       0.77      0.75      0.72      2616